name: Build Docker Image

on:
  push:
    tags:
      - v*

jobs:
  # Push image to Package Registries (GitHub Packages, ghcr.io, and DockerHub).
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile.gtk3 --tag vasilev/palemoon

      - name: Log into registries
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/palemoon

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag vasilev/palemoon $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          
          IMAGENAME='vasilev/palemoon'
          for REPO in '' 'ghcr.io/'
          do
          REPO_IMAGENAME=$REPO$IMAGENAME
          VERSIONED_IMAGENAME="$REPO_IMAGENAME:$VERSION"
          echo VERSIONED_IMAGENAME=$VERSIONED_IMAGENAME
          
          docker tag $IMAGENAME $REPO_IMAGENAME
          docker tag $IMAGENAME $VERSIONED_IMAGENAME
          docker push $REPO_IMAGENAME:latest
          docker push $VERSIONED_IMAGENAME
          done
