name: _Manually_ build Docker image for Pale Moon browser with Gnash plugin

on:
  repository_dispatch:
    types: ['build-with-gnashplugin']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile.gnashplugin --tag vasilev/palemoon
      - name: Log into registry
        run: | 
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push image
        run: |
          # Get the version from client payload
          VERSION=${{ github.event.client_payload.version }}
          # Use 'latest' if provided value is empty
          : ${VERSION:='latest'}
          TAGGED_IMAGENAME="vasilev/palemoon:$VERSION-gnashplugin-$(date -I)"
          echo TAGGED_IMAGENAME=$TAGGED_IMAGENAME
          docker tag vasilev/palemoon $TAGGED_IMAGENAME
          docker push $TAGGED_IMAGENAME
