name: _Manually_ build Docker image for Pale Moon browser with Flash plugin

on:
  repository_dispatch:
    types: ['build-with-flashplugin']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile.flashplugin --tag vasilev/palemoon
      - name: Log into registry
        run: | 
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push image
        run: |
          # Get the version from client payload
          VERSION=${{ github.event.client_payload.version }}
          # Use 'latest' if provided value is empty
          : ${VERSION:='latest'}
          echo VERSION=$VERSION
          docker tag vasilev/palemoon vasilev/palemoon:$VERSION-flashplugin
          docker push vasilev/palemoon:$VERSION-flashplugin
