name: Build Docker Image

on:
  push:
    tags:
      - v*

jobs:
  # Push image to Package Registries (GitHub and DockerHub).
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag vasilev/palemoon

      - name: Log into registries
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/palemoon

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag vasilev/palemoon $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker tag vasilev/palemoon vasilev/palemoon:$VERSION
          docker push vasilev/palemoon:$VERSION
          docker push vasilev/palemoon:latest
